import { describe, it, expect } from "vitest";
import JSZip from "jszip";
import {
  parseSlicerText,
  parseSlicerFile,
  cleanFileNameToTitle,
  convertMetersToGrams,
  decodeGcodeHeadTail
} from "../src/utils/slicerParser";

describe("slicerParser", () => {
  it("cleanFileNameToTitle deve higienizar nomes de arquivos", () => {
    expect(cleanFileNameToTitle("danger+dragon+multicolor.3mf")).toBe("Danger Dragon Multicolor");
    expect(cleanFileNameToTitle("meu_modelo_articulado.gcode")).toBe("Meu Modelo Articulado");
  });

  it("convertMetersToGrams deve calcular peso de filamento a partir de metros", () => {
    // 1 metro de PLA 1.75mm (densidade 1.24): ~2.98g
    expect(convertMetersToGrams(1, "PLA")).toBeCloseTo(2.98, 1);
    // 2.5 metros: ~7.46g
    expect(convertMetersToGrams(2.5, "PLA")).toBeCloseTo(7.46, 1);
    // 0 metros
    expect(convertMetersToGrams(0)).toBe(0);
  });

  it("parseSlicerText deve extrair dados de texto do MakerWorld", () => {
    const makerWorldPrint = `
      multicolor
      jars_2003
      A1,A1 mini,X1,H2C,P1S,X1 Carbon
      1 plate  1.4 h  0.4 mm  17 g
      AMS  PLA | 14 g  PLA | 3 g
    `;
    const res = parseSlicerText(makerWorldPrint);
    expect(res.detected).toBe(true);
    expect(res.filamentGrams).toBe(17);
    expect(res.timeHours).toBeCloseTo(1.4);
    expect(res.partsBreakdown?.length).toBe(2);
    expect(res.partsBreakdown?.[0].filamentGrams).toBe(14);
    expect(res.partsBreakdown?.[1].filamentGrams).toBe(3);
  });

  it("parseSlicerText deve extrair dados de G-code Bambu/Orca", () => {
    const bambuGcode = `
      ; total filament used [g] = 76.5
      ; estimated printing time = 5h40min
    `;
    const res = parseSlicerText(bambuGcode);
    expect(res.detected).toBe(true);
    expect(res.slicerType).toBe("Bambu/Orca");
    expect(res.filamentGrams).toBe(76.5);
    expect(res.timeHours).toBeCloseTo(5 + 40 / 60);
  });

  it("parseSlicerText deve detectar PrusaSlicer e tempos com dias/segundos", () => {
    const prusaGcode = `
      ; generated by PrusaSlicer 2.7.0
      ; filament used [g] = 42.5
      ; estimated printing time (normal mode) = 1d 2h 30m 15s
    `;
    const res = parseSlicerText(prusaGcode);
    expect(res.detected).toBe(true);
    expect(res.slicerType).toBe("Prusa/SuperSlicer");
    expect(res.filamentGrams).toBe(42.5);
    expect(res.timeHours).toBeCloseTo(26.504166, 4);
  });

  it("parseSlicerText deve converter filamento em metros do Cura para gramas", () => {
    const curaGcode = `
      ;Generated with Cura_SteamEngine 5.4.0
      ;TIME:7200
      ;Filament used: 2.5m
    `;
    const res = parseSlicerText(curaGcode);
    expect(res.detected).toBe(true);
    expect(res.slicerType).toBe("Cura");
    expect(res.timeHours).toBe(2);
    expect(res.filamentGrams).toBeCloseTo(7.46, 1);
    expect(res.needsManualTimeOrWeight).toBe(false);
  });

  it("parseSlicerText deve tratar múltiplos extrusores no Cura", () => {
    const curaMulti = `
      ;TIME:3600
      ;Filament used: 2.0m, 1.0m
    `;
    const res = parseSlicerText(curaMulti);
    expect(res.detected).toBe(true);
    expect(res.slicerType).toBe("Cura");
    expect(res.timeHours).toBe(1);
    // 3.0m de PLA: ~8.95g
    expect(res.filamentGrams).toBeCloseTo(8.95, 1);
  });

  it("parseSlicerFile deve ler metadados de arquivo 3MF sintético", async () => {
    const zip = new JSZip();
    zip.file("3D/3dmodel.model", `<?xml version="1.0" encoding="UTF-8"?>
      <model>
        <metadata name="Title">Dragão Articulado</metadata>
        <metadata name="Designer">ArtgianStudio</metadata>
      </model>
    `);
    zip.file("Metadata/plate_1.gcode", `
      ; total filament used [g] = 50.0
      ; estimated printing time = 3h30min
    `);
    const zipBlob = await zip.generateAsync({ type: "blob" });
    const file = new File([zipBlob], "dragao.3mf", { type: "application/octet-stream" });

    const res = await parseSlicerFile(file);
    expect(res.detected).toBe(true);
    expect(res.modelTitle).toBe("Dragão Articulado");
    expect(res.designer).toBe("ArtgianStudio");
    expect(res.filamentGrams).toBe(50);
    expect(res.timeHours).toBeCloseTo(3.5);
  });

  it("parseSlicerFile deve somar múltiplas placas no 3MF (multi-plate)", async () => {
    const zip = new JSZip();
    zip.file("3D/3dmodel.model", `<?xml version="1.0" encoding="UTF-8"?>
      <model>
        <metadata name="Title">Vaso Geométrico</metadata>
      </model>
    `);
    zip.file("Metadata/plate_1.gcode", `
      ; total filament used [g] = 25.0
      ; estimated printing time = 1h30min
    `);
    zip.file("Metadata/plate_2.gcode", `
      ; total filament used [g] = 35.0
      ; estimated printing time = 2h00min
    `);
    const zipBlob = await zip.generateAsync({ type: "blob" });
    const file = new File([zipBlob], "vaso.3mf", { type: "application/octet-stream" });

    const res = await parseSlicerFile(file);
    expect(res.detected).toBe(true);
    expect(res.filamentGrams).toBe(60.0);
    expect(res.timeHours).toBeCloseTo(3.5);
    expect(res.partsBreakdown?.length).toBe(2);
    expect(res.partsBreakdown?.[0].name).toContain("Placa 1");
    expect(res.partsBreakdown?.[0].filamentGrams).toBe(25.0);
    expect(res.partsBreakdown?.[1].name).toContain("Placa 2");
    expect(res.partsBreakdown?.[1].filamentGrams).toBe(35.0);
  });

  it("parseSlicerFile deve suportar XML real do Bambu Studio em slice_info.config", async () => {
    const zip = new JSZip();
    zip.file("3D/3dmodel.model", `<?xml version="1.0" encoding="UTF-8"?>
      <model>
        <metadata name="Title">Luminária Lua</metadata>
      </model>
    `);
    const xmlConfig = `<?xml version="1.0" encoding="UTF-8"?>
      <config>
        <plate>
          <metadata key="prediction" value="5025"/>
          <metadata key="weight" value="17.43"/>
          <filament id="1" type="PLA" color="#FFFFFF" used_m="5.2" used_g="14.20"/>
          <filament id="2" type="PLA" color="#000000" used_m="1.1" used_g="3.23"/>
        </plate>
      </config>
    `;
    zip.file("Metadata/slice_info.config", xmlConfig);
    const zipBlob = await zip.generateAsync({ type: "blob" });
    const file = new File([zipBlob], "luminaria.3mf", { type: "application/octet-stream" });

    const res = await parseSlicerFile(file);
    expect(res.detected).toBe(true);
    expect(res.slicerType).toBe("Bambu/Orca");
    expect(res.filamentGrams).toBe(17.43);
    // 5025 segundos = 1.3958 horas
    expect(res.timeHours).toBeCloseTo(5025 / 3600);
    expect(res.partsBreakdown?.length).toBe(2);
    expect(res.partsBreakdown?.[0].filamentGrams).toBe(14.2);
    expect(res.partsBreakdown?.[1].filamentGrams).toBe(3.23);
  });

  it("decodeGcodeHeadTail mantém cabeçalho e rodapé de G-codes grandes", () => {
    const filler = "G1 X10 Y10 E0.5\n".repeat(40000); // ~640 KB de movimentos
    const text = "; HEADER_BLOCK_START\n" + filler + "; filament used [g] = 12.3\n";
    const bytes = new TextEncoder().encode(text);
    const decoded = decodeGcodeHeadTail(bytes);
    expect(decoded.length).toBeLessThan(bytes.length);
    expect(decoded).toContain("; HEADER_BLOCK_START");
    expect(decoded).toContain("; filament used [g] = 12.3");

    const small = new TextEncoder().encode("; estimated printing time = 1h");
    expect(decodeGcodeHeadTail(small)).toBe("; estimated printing time = 1h");
  });

  it("parseSlicerFile lê metadados no rodapé de placas grandes dentro do 3MF", async () => {
    const zip = new JSZip();
    const filler = "G1 X10 Y10 E0.5\n".repeat(40000);
    zip.file("Metadata/plate_1.gcode", "; generated by PrusaSlicer 2.7.0\n" + filler +
      "; filament used [g] = 33.3\n; estimated printing time (normal mode) = 2h 15m\n");
    const zipBlob = await zip.generateAsync({ type: "blob" });
    const file = new File([zipBlob], "grande.3mf", { type: "application/octet-stream" });

    const res = await parseSlicerFile(file);
    expect(res.detected).toBe(true);
    expect(res.filamentGrams).toBeCloseTo(33.3);
    expect(res.timeHours).toBeCloseTo(2.25);
    expect(res.modelTitle).toBe("Grande");
  });
});
